const FUNCTIONS = [
  {
    name: 'spec.set_status',
    label: 'Alterar status da spec',
    method: 'POST',
    endpoint: '/api/specs/:slug/status',
    input: { slug: 'string', stage: 'spec|plan|tasks', status: 'draft|review|approved|implementing|done|abandoned' },
    visibleIn: ['Specs'],
    description: 'Executa spec-cli set-status e publica spec.status_changed para o front atualizar em realtime.',
  },
  {
    name: 'handoff.transition',
    label: 'Transicionar handoff',
    method: 'POST',
    endpoint: '/api/handoffs/:id/transition',
    input: { id: 'number', to: 'in_progress|done|cancelled' },
    visibleIn: ['Handoffs', 'Agentes'],
    description: 'Chama agent-router para mover uma tarefa entre estados e emitir handoff.transitioned.',
  },
  {
    name: 'memory.search',
    label: 'Buscar memória universal',
    method: 'GET',
    endpoint: '/api/memory/search?q=&kind=&project=&limit=',
    input: { q: 'string', kind: 'optional string', project: 'optional string', limit: '1..100' },
    visibleIn: ['Memória'],
    description: 'Consulta o índice FTS5 do universal.db sem ler Markdown avulso no client.',
  },
  {
    name: 'docs.read',
    label: 'Abrir documento',
    method: 'GET',
    endpoint: '/api/docs/read?path=',
    input: { path: 'docs|memory|prompts/*.md' },
    visibleIn: ['Documentação'],
    description: 'Lê Markdown versionado com allowlist de raiz e proteção contra path traversal.',
  },
  {
    name: 'agent.inspect',
    label: 'Inspecionar agente',
    method: 'GET',
    endpoint: '/api/agents/:name',
    input: { name: 'orchestrator|context-engineer|sdd-architect|product|marketing|governance' },
    visibleIn: ['Agentes'],
    description: 'Mostra prompt Claude, prompt portátil e fila de handoffs por agente.',
  },
  {
    name: 'llm.assign_role',
    label: 'Definir LLM por papel',
    method: 'POST',
    endpoint: '/api/llm-routing/:role',
    input: { role: 'string', provider: 'codex|claude|gemini-cli|deepseek|minimax|mistral|qwen|ollama|openrouter|together|groq|xai|cohere|perplexity|manual', model: 'string', command: 'string', taskTypes: 'string[]' },
    visibleIn: ['Agentes', 'Funções'],
    description: 'Persiste qual CLI/modelo deve atender cada papel, inclusive papéis customizados como ceo ou cto.',
  },
  {
    name: 'workflow.start_project',
    label: 'Iniciar projeto com LLMs',
    method: 'POST',
    endpoint: '/api/workflow/start-project',
    input: { projectName: 'string', initialPrompt: 'string', roles: 'string[]', sprintGoal: 'string', nextSprintDetails: 'string' },
    visibleIn: ['Workflow', 'Funções'],
    description: 'Cria estrutura do projeto, prompt inicial, current-sprint, comandos por provedor e sincroniza o universal.db.',
  },
  {
    name: 'workflow.update_step',
    label: 'Atualizar Kanban pelo retorno da LLM',
    method: 'POST',
    endpoint: '/api/workflow/:project/kanban/:step',
    input: { status: 'todo|running|blocked|review|done', details: 'string', llmReturn: 'string' },
    visibleIn: ['Workflow'],
    description: 'Registra o retorno da LLM como run Markdown, atualiza status do Kanban e sincroniza SQLite.',
  },
  {
    name: 'workflow.comment_sprint',
    label: 'Comentar próxima sprint',
    method: 'POST',
    endpoint: '/api/workflow/:project/comments',
    input: { comment: 'string', nextSprintDetails: 'string' },
    visibleIn: ['Workflow'],
    description: 'Adiciona comentários e detalhes da próxima sprint em Markdown versionado e no workflow.json.',
  },
  {
    name: 'workflow.run_llm',
    label: 'Executar LLM por papel',
    method: 'POST',
    endpoint: '/api/workflow/:project/run/:role',
    input: { step: 'string', prompt: 'string' },
    visibleIn: ['Workflow'],
    description: 'Executa somente a CLI roteada para o papel, transmite stdout/stderr por SSE e grava o run em Markdown.',
  },
  {
    name: 'gsd.plan',
    label: 'Criar runbook GSD',
    method: 'CLI',
    endpoint: 'npm run gsd:plan -- <slug> "<objetivo>"',
    input: { slug: 'project slug', objetivo: 'string' },
    visibleIn: ['Workflow', 'Funções', 'Harness'],
    description: 'Cria .context/gsd-<slug>.md com gates verificáveis do briefing até governance.',
  },
  {
    name: 'gsd.handoff',
    label: 'Registrar handoff GSD/Hermes',
    method: 'CLI',
    endpoint: 'npm run gsd:handoff -- <spec|plan|implement|review> <slug>',
    input: { phase: 'spec|plan|implement|review', slug: 'project slug', context: 'optional string' },
    visibleIn: ['Workflow', 'Handoffs', 'Harness'],
    description: 'Usa Hermes para registrar handoffs padronizados com os 7 campos do ADR-0005.',
  },
  {
    name: 'gsd.check',
    label: 'Validar gates GSD',
    method: 'CLI',
    endpoint: 'npm run gsd:check -- <slug> <brief.md>',
    input: { slug: 'project slug', brief: 'design-md/examples/agent-console-brief.md' },
    visibleIn: ['Workflow', 'Governance', 'Harness'],
    description: 'Valida runbook, spec e brief visual antes de entregar para Governance.',
  },
  {
    name: 'design.select',
    label: 'Escolher referência design-md',
    method: 'CLI',
    endpoint: 'npm run design:select -- <surface> <tone>',
    input: { surface: 'agent-console|dashboard|docs|landing|tool|fintech|premium', tone: 'tecnico|premium|minimal' },
    visibleIn: ['Stack', 'Funções', 'Harness'],
    description: 'Sugere referências locais de design-md para a superfície antes de gerar o brief visual.',
  },
  {
    name: 'design.check',
    label: 'Validar brief visual',
    method: 'CLI',
    endpoint: 'npm run design:check -- <brief.md>',
    input: { brief: 'design-md/BRIEF-TEMPLATE.md preenchido' },
    visibleIn: ['Stack', 'Workflow', 'Harness'],
    description: 'Confere campos mínimos do brief visual, incluindo tokens, componentes, estados e critérios de aceite.',
  },
  {
    name: 'stack.suggest',
    label: 'Sugerir stack por adaptação',
    method: 'POST',
    endpoint: '/api/stacks/suggest',
    input: { projectType: 'string', constraints: 'string', developerPreference: 'string' },
    visibleIn: ['Stack'],
    description: 'Gera uma sugestão local de stack considerando contexto, restrições e preferência do dev.',
  },
  {
    name: 'stack.save',
    label: 'Salvar stack e boilerplate',
    method: 'POST',
    endpoint: '/api/stacks/:project',
    input: { aiSuggestion: 'object', developerStack: 'string', selectedBoilerplate: 'string', designSystem: 'object', notes: 'string' },
    visibleIn: ['Stack'],
    description: 'Persiste stack.md, gera design-brief.md e sincroniza o SQLite.',
  },
];

export default async function functionsRoutes(app) {
  app.get('/api/functions', async () => FUNCTIONS);
}
